chore: updates documentation
dhis2/cli pull request #393
Opened 2020-12-01 09:58 UTC by paschalidi

Hey this updates the `release` part of the documentation a little bit. Please have a look and let me know if there is anything you would phrase differently

2020-12-04 12:24 UTC, Mohammer5 requested changes
I think we should mention that the package.json needs to contain the following in case the module should be published on npm:

```json
{
  "private": false,
  "publishConfig": {
    "access": "public"
  }
}
```

2020-12-04 12:24 UTC, Mohammer5 commented on docs/commands/d2-utils-release.md
> +3. The versions in the `package.json` will be updated as well.
This does also apply to yarn monorepos. The release command will update all the versions of the workspaces' package.json files to the same, new version.

2020-12-09 16:36 UTC, paschalidi commented
@Mohammer5 thanks for looking into it. I have applied what you suggested. This is how this will look now 👇   
![image](https://user-images.githubusercontent.com/4181674/101658063-893f2e00-3a3c-11eb-88c1-0732deb04d5d.png)

2020-12-10 09:37 UTC, Mohammer5 approved these changes
LGTM

2020-12-10 09:40 UTC, paschalidi commented
So now the question is why these jobs run for ever. @varl any ideas?

2021-06-09 21:07 UTC, closed without merging