feat(cli): prefer project-local tools
dhis2/cli pull request #514
Opened 2021-11-15 10:37 UTC by varl

Increases the utility of the global d2 tool for developers by preferring
the version of the CLI tool that is installed over the globally bundled
one.

Before this change these two commands run in the same project can yield
different results:

    d2 style check          # global
    yarn d2-style check     # local

After the change, they will both use the local version:

    d2 style check          # local
    yarn d2-style check     # local

Jira-ticket-key: CLI-68
Jira-ticket-URL: https://jira.dhis2.org/browse/CLI-68

2021-11-15 10:42 UTC, amcgee requested changes
Implementation looks great! Can we move this to `cli-helpers-engine` though and then use it to load all sub-modules?  For example, this will find a local version of `d2-app` but not `d2-app-scripts` which would be very handy

2021-11-15 10:43 UTC, amcgee commented
Also, should we maybe have a flag to short-circuit the lookup and revert to the global version?

2021-11-15 11:03 UTC, mediremi approved these changes

2021-11-15 11:09 UTC, varl commented
> Also, should we maybe have a flag to short-circuit the lookup and revert to the global version?

I was thinking of adding `--global` to do that, or `--prefer-global` with a short alias (`-g`, probably). 

I had one variant that did this but I think we'd need to manually parse `yargs.argv` (as it's not final) and pass it from the builder to the `load` function. I can see if the situation changes when we move it to engine.

2021-11-15 11:11 UTC, varl commented
> Implementation looks great! Can we move this to `cli-helpers-engine` though and then use it to load all sub-modules? For example, this will find a local version of `d2-app` but not `d2-app-scripts` which would be very handy

Well, that was quick !

Sure, I can move it. :+1:

2021-11-15 13:55 UTC, varl commented
> Also, should we maybe have a flag to short-circuit the lookup and revert to the global version?

This happens in the builder phase, before the arguments have been parsed. Moving the code later in `makeEntrypoint` causes problems with yargs, and calling `.argv` / `.parse()` in the builder functions is [not recommended](https://github.com/yargs/yargs/blob/main/docs/api.md#argv):

> **Note**: `.argv` should only be used at the top level, not inside a command's builder function.

And I can verify that it is indeed problematic.

The `loadModule` function accepts a boolean to toggle `preferLocal` on/off, so the functionality is there, and would be great if we could get it from yargs directly as it would be very easy to integrate:

```js
const globalLoader = loadModule({
    parentModule: __filename,
    preferLocal: yargs.argv.local,
})
```

2021-11-18 13:58 UTC, varl commented
@amcgee @mediremi Updated to use the CLI Engine function.

2021-11-18 14:19 UTC, mediremi approved these changes

2021-11-22 13:59 UTC, varl commented
@amcgee could you re-review this ? Currently blocked by the old review.

2021-11-29 15:18 UTC, amcgee approved these changes
Awesome 😎

2021-11-29 19:20 UTC, merged